name: Merge master into staging & sandbox on PR merge

on:
  push:
    branches:
      - master

jobs:
  backmerge-staging:
    uses: paper-indonesia/paper-devops/.github/workflows/backmerge-staging.yml@master
    secrets:
      SLACKNOTIF_GITHUB_SECRET: ${{ secrets.SLACKNOTIF_GITHUB_SECRET }}
